CFLAGS = -O3 -march=native -ffast-math -flto -funroll-loops

present_cbc:
	g++ $(CFLAGS) -o present_cbc present_cbc.cpp present.hpp

present_ctr:
	g++ $(CFLAGS) -o present_ctr present_ctr.cpp present.hpp